
-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE 01. Organization.organization_types (
  id bigint NOT NULL DEFAULT nextval('"01. Organization".organization_types_id_seq'::regclass),
  type_code character varying NOT NULL UNIQUE,
  display_name character varying NOT NULL,
  description text,
  icon_name character varying,
  color_hex character varying,
  can_list_vehicles boolean NOT NULL DEFAULT false,
  can_list_products boolean NOT NULL DEFAULT false,
  can_request_quotes boolean NOT NULL DEFAULT false,
  can_receive_quotes boolean NOT NULL DEFAULT false,
  requires_verification boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_types_pkey PRIMARY KEY (id)
);
CREATE TABLE 01. Organization.organization_users (
  id bigint NOT NULL DEFAULT nextval('"01. Organization".organization_users_id_seq'::regclass),
  organization_id bigint NOT NULL,
  user_id uuid NOT NULL,
  role character varying NOT NULL DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['owner'::character varying::text, 'admin'::character varying::text, 'member'::character varying::text, 'viewer'::character varying::text])),
  permissions jsonb DEFAULT '{}'::jsonb,
  invited_by uuid,
  invited_at timestamp with time zone DEFAULT now(),
  joined_at timestamp with time zone,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'active'::character varying::text, 'suspended'::character varying::text, 'removed'::character varying::text])),
  email_notifications boolean DEFAULT true,
  sms_notifications boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_users_pkey PRIMARY KEY (id),
  CONSTRAINT organization_users_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id),
  CONSTRAINT organization_users_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES 01. Organization.organizations(id),
  CONSTRAINT organization_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT fk_organization_users_user_id FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE 01. Organization.organizations (
  id bigint NOT NULL DEFAULT nextval('"01. Organization".organizations_id_seq'::regclass),
  organization_type_id bigint NOT NULL,
  organization_name character varying NOT NULL,
  legal_entity_name character varying,
  display_name character varying,
  slug character varying NOT NULL UNIQUE CHECK (slug::text ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text),
  primary_email character varying NOT NULL CHECK (primary_email::text ~~ '%@%.%'::text),
  primary_phone character varying,
  primary_phone_ext character varying,
  primary_phone_accepts_sms boolean DEFAULT true,
  secondary_phone character varying,
  secondary_phone_ext character varying,
  address_line1 character varying,
  address_line2 character varying,
  city character varying,
  state_province character varying,
  postal_code character varying,
  country character varying DEFAULT 'US'::character varying,
  latitude numeric,
  longitude numeric,
  timezone character varying DEFAULT 'America/Chicago'::character varying,
  preferred_currency character varying DEFAULT 'USD'::character varying,
  naics_code character varying,
  website_url character varying,
  logo_url character varying,
  facebook_url character varying,
  linkedin_url character varying,
  twitter_handle character varying,
  instagram_handle character varying,
  tiktok_handle character varying,
  youtube_channel_url character varying,
  is_verified boolean NOT NULL DEFAULT false,
  verified_at timestamp with time zone,
  verified_by uuid,
  verification_notes text,
  status character varying NOT NULL DEFAULT 'pending_verification'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying::text, 'suspended'::character varying::text, 'inactive'::character varying::text, 'pending_verification'::character varying::text, 'rejected'::character varying::text])),
  status_reason text,
  status_changed_at timestamp with time zone,
  status_changed_by uuid,
  subscription_tier character varying DEFAULT 'free'::character varying CHECK (subscription_tier::text = ANY (ARRAY['free'::character varying::text, 'basic'::character varying::text, 'premium'::character varying::text, 'enterprise'::character varying::text])),
  subscription_starts_at timestamp with time zone,
  subscription_expires_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  tax_id character varying,
  business_hours jsonb DEFAULT '{}'::jsonb,
  parent_organization_id bigint,
  is_dealer_group boolean DEFAULT false,
  group_display_name character varying,
  sales_territory_states ARRAY,
  last_profile_update_at timestamp with time zone,
  last_profile_update_by uuid,
  profile_completion_percentage integer DEFAULT 0,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT organizations_organization_type_id_fkey FOREIGN KEY (organization_type_id) REFERENCES 01. Organization.organization_types(id),
  CONSTRAINT organizations_status_changed_by_fkey FOREIGN KEY (status_changed_by) REFERENCES auth.users(id),
  CONSTRAINT organizations_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES auth.users(id),
  CONSTRAINT organizations_parent_organization_id_fkey FOREIGN KEY (parent_organization_id) REFERENCES 01. Organization.organizations(id),
  CONSTRAINT organizations_last_profile_update_by_fkey FOREIGN KEY (last_profile_update_by) REFERENCES auth.users(id)
);

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE 02a. Dealership.dealer_codes (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  dealer_id bigint NOT NULL,
  organization_id bigint NOT NULL,
  make character varying NOT NULL,
  dealer_code character varying NOT NULL,
  is_primary boolean DEFAULT false,
  is_active boolean DEFAULT true,
  certified_date date,
  certification_expires_at date,
  default_price_level character varying DEFAULT '630'::character varying,
  can_order_fleet boolean DEFAULT false,
  can_order_government boolean DEFAULT false,
  uses_b4a boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  make_id bigint NOT NULL,
  certification_level character varying,
  annual_volume_commitment integer,
  volume_tier character varying,
  region_code character varying,
  district_code character varying,
  zone_manager_name character varying,
  zone_manager_email character varying,
  programs_enrolled jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT dealer_codes_pkey PRIMARY KEY (id),
  CONSTRAINT dealer_codes_dealer_id_fkey FOREIGN KEY (dealer_id) REFERENCES 02a. Dealership.dealers(id),
  CONSTRAINT dealer_codes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES 01. Organization.organizations(id),
  CONSTRAINT dealer_codes_make_id_fkey FOREIGN KEY (make_id) REFERENCES 03. Vehicle Data.makes(id)
);
CREATE TABLE 02a. Dealership.dealer_inventory (
  id bigint NOT NULL DEFAULT nextval('"02a. Dealership".dealer_inventory_id_seq'::regclass),
  dealer_id bigint NOT NULL,
  organization_id bigint NOT NULL,
  dealer_order_id bigint,
  oem_invoice_id bigint,
  complete_configuration_id bigint,
  listing_id bigint,
  vin character varying NOT NULL UNIQUE,
  stock_number character varying,
  inventory_status character varying NOT NULL DEFAULT 'in_stock'::character varying CHECK (inventory_status::text = ANY (ARRAY['on_order'::character varying, 'in_transit'::character varying, 'in_stock'::character varying, 'at_upfitter'::character varying, 'sold'::character varying, 'demo'::character varying, 'loaner'::character varying, 'transferred'::character varying, 'removed'::character varying]::text[])),
  received_date date,
  in_stock_date date,
  sold_date date,
  removed_date date,
  lot_location character varying,
  location_notes text,
  condition character varying DEFAULT 'new'::character varying CHECK (condition::text = ANY (ARRAY['new'::character varying, 'used'::character varying, 'demo'::character varying, 'damaged'::character varying, 'needs_service'::character varying]::text[])),
  mileage integer DEFAULT 0,
  floor_plan_status character varying CHECK (floor_plan_status::text = ANY (ARRAY['not_floored'::character varying, 'floored'::character varying, 'paid_off'::character varying]::text[])),
  floor_plan_date date,
  floor_plan_interest_to_date numeric DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT dealer_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT dealer_inventory_dealer_id_fkey FOREIGN KEY (dealer_id) REFERENCES 02a. Dealership.dealers(id),
  CONSTRAINT dealer_inventory_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES 01. Organization.organizations(id),
  CONSTRAINT dealer_inventory_dealer_order_id_fkey FOREIGN KEY (dealer_order_id) REFERENCES 02a. Dealership.dealer_orders(id),
  CONSTRAINT dealer_inventory_complete_configuration_id_fkey FOREIGN KEY (complete_configuration_id) REFERENCES 05. Completed Unit Configuration.complete_configurations(id),
  CONSTRAINT dealer_inventory_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES 02a. Dealership.vehicle_listings(id),
  CONSTRAINT dealer_inventory_oem_invoice_id_fkey FOREIGN KEY (oem_invoice_id) REFERENCES 02a. Dealership.oem_invoices(id)
);
CREATE TABLE 02a. Dealership.dealer_locations (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  dealer_id bigint NOT NULL,
  organization_id bigint NOT NULL,
  location_name character varying NOT NULL,
  location_type character varying CHECK (location_type::text = ANY (ARRAY['main'::character varying, 'satellite'::character varying, 'service_only'::character varying, 'parts_only'::character varying]::text[])),
  address_line1 character varying,
  address_line2 character varying,
  city character varying,
  state_province character varying,
  postal_code character varying,
  country character varying DEFAULT 'US'::character varying,
  latitude numeric,
  longitude numeric,
  phone character varying,
  phone_ext character varying,
  fax character varying,
  email character varying,
  business_hours jsonb DEFAULT '{"friday": {"open": "08:00", "close": "18:00", "closed": false}, "monday": {"open": "08:00", "close": "18:00", "closed": false}, "sunday": {"closed": true}, "tuesday": {"open": "08:00", "close": "18:00", "closed": false}, "saturday": {"open": "09:00", "close": "17:00", "closed": false}, "thursday": {"open": "08:00", "close": "18:00", "closed": false}, "wednesday": {"open": "08:00", "close": "18:00", "closed": false}}'::jsonb,
  is_primary boolean DEFAULT false,
  is_active boolean DEFAULT true,
  manager_name character varying,
  manager_email character varying,
  manager_phone character varying,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT dealer_locations_pkey PRIMARY KEY (id),
  CONSTRAINT dealer_locations_dealer_id_fkey FOREIGN KEY (dealer_id) REFERENCES 02a. Dealership.dealers(id),
  CONSTRAINT dealer_locations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES 01. Organization.organizations(id)
);
CREATE TABLE 02a. Dealership.dealer_orders (
  id bigint NOT NULL DEFAULT nextval('"02a. Dealership".dealer_orders_id_seq'::regclass),
  dealer_id bigint NOT NULL,
  organization_id bigint NOT NULL,
  vehicle_config_id bigint,
  complete_configuration_id bigint,
  order_number character varying UNIQUE,
  ford_order_number character varying,
  vin character varying UNIQUE CHECK (vin::text ~ '^[A-HJ-NPR-Z0-9]{17}$'::text),
  stock_number character varying,
  order_type character varying NOT NULL CHECK (order_type::text = ANY (ARRAY['stock'::character varying, 'retail'::character varying, 'fleet'::character varying, 'demo'::character varying, 'loaner'::character varying, 'allocation'::character varying]::text[])),
  order_status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (order_status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'scheduled'::character varying, 'in_production'::character varying, 'completed'::character varying, 'in_transit'::character varying, 'delivered'::character varying, 'cancelled'::character varying, 'converted_to_stock'::character varying]::text[])),
  order_type_code character varying,
  ramp_code character varying,
  batch_id character varying,
  price_level character varying,
  order_date date NOT NULL,
  order_confirmed_date date,
  production_scheduled_date date,
  production_start_date date,
  production_completed_date date,
  estimated_delivery_date date,
  actual_delivery_date date,
  final_assembly_plant character varying,
  assembly_date date,
  transit_days integer,
  customer_name character varying,
  customer_email character varying,
  customer_phone character varying,
  customer_address text,
  is_fleet_customer boolean DEFAULT false,
  fleet_name character varying,
  finance_type character varying CHECK (finance_type::text = ANY (ARRAY['cash'::character varying, 'finance'::character varying, 'lease'::character varying, 'ford_credit'::character varying, 'outside_lender'::character varying, 'fleet_account'::character varying]::text[])),
  finance_company character varying,
  finance_account character varying,
  pricing_plan character varying,
  is_employee_pricing boolean DEFAULT false,
  is_supplier_pricing boolean DEFAULT false,
  is_partner_pricing boolean DEFAULT false,
  is_fleet_order boolean DEFAULT false,
  fleet_incentive_code character varying,
  fleet_reference_number character varying,
  is_government_order boolean DEFAULT false,
  internal_notes text,
  customer_notes text,
  special_instructions text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  item_number character varying,
  CONSTRAINT dealer_orders_pkey PRIMARY KEY (id),
  CONSTRAINT dealer_orders_dealer_id_fkey FOREIGN KEY (dealer_id) REFERENCES 02a. Dealership.dealers(id),
  CONSTRAINT dealer_orders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES 01. Organization.organizations(id),
  CONSTRAINT dealer_orders_vehicle_config_id_fkey FOREIGN KEY (vehicle_config_id) REFERENCES 03. Vehicle Data.vehicle_config(id),
  CONSTRAINT dealer_orders_complete_configuration_id_fkey FOREIGN KEY (complete_configuration_id) REFERENCES 05. Completed Unit Configuration.complete_configurations(id),
  CONSTRAINT dealer_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE 02a. Dealership.dealers (
  id bigint NOT NULL DEFAULT nextval('"02a. Dealership".dealers_id_seq'::regclass),
  organization_id bigint NOT NULL UNIQUE,
  business_type character varying CHECK (business_type::text = ANY (ARRAY['franchise_dealer'::character varying::text, 'independent_dealer'::character varying::text, 'fleet_remarketer'::character varying::text, 'broker'::character varying::text, 'leasing_company'::character varying::text, 'rental_company'::character varying::text, 'other'::character varying::text])),
  dealer_license_number character varying,
  dealer_license_state character varying,
  dealer_license_expires_at date,
  tax_id character varying,
  duns_number character varying,
  specializations ARRAY,
  makes_carried ARRAY,
  average_inventory_count integer,
  lot_capacity integer,
  can_special_order boolean DEFAULT true,
  accepts_trade_ins boolean DEFAULT true,
  has_service_department boolean DEFAULT false,
  has_parts_department boolean DEFAULT false,
  has_body_shop boolean DEFAULT false,
  can_install_upfits boolean DEFAULT false,
  typical_delivery_days integer,
  sales_territory_states ARRAY,
  delivery_available boolean DEFAULT true,
  delivery_radius_miles integer,
  delivery_fee numeric,
  current_promotions text,
  accepts_fleet_inquiries boolean DEFAULT true,
  minimum_fleet_size integer,
  fleet_discount_percentage numeric,
  business_hours jsonb DEFAULT '{"friday": {"open": "08:00", "close": "18:00", "closed": false}, "monday": {"open": "08:00", "close": "18:00", "closed": false}, "sunday": {"closed": true}, "tuesday": {"open": "08:00", "close": "18:00", "closed": false}, "saturday": {"open": "09:00", "close": "17:00", "closed": false}, "thursday": {"open": "08:00", "close": "18:00", "closed": false}, "wednesday": {"open": "08:00", "close": "18:00", "closed": false}}'::jsonb,
  certifications ARRAY,
  awards ARRAY,
  total_listings_count integer DEFAULT 0,
  active_listings_count integer DEFAULT 0,
  sold_count_30d integer DEFAULT 0,
  sold_count_lifetime integer DEFAULT 0,
  average_response_time_hours numeric,
  customer_satisfaction_score numeric,
  auto_respond_inquiries boolean DEFAULT false,
  inquiry_email_notification boolean DEFAULT true,
  weekly_performance_report boolean DEFAULT true,
  allow_price_negotiations boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  dealer_code character varying UNIQUE,
  ford_dealer_code character varying UNIQUE,
  default_price_level character varying DEFAULT '630'::character varying,
  can_order_fleet boolean DEFAULT false,
  can_order_government boolean DEFAULT false,
  uses_b4a boolean DEFAULT true,
  floor_plan_company character varying,
  floor_plan_account character varying,
  last_profile_update_at timestamp with time zone,
  last_profile_update_by uuid,
  profile_completion_percentage integer DEFAULT 0,
  fein_number character varying,
  sam_registration boolean DEFAULT false,
  sam_expiration_date date,
  cage_code character varying,
  ford_pro_elite boolean DEFAULT false,
  gm_fleet_certified boolean DEFAULT false,
  ram_commercial_certified boolean DEFAULT false,
  preferred_upfitter_ids ARRAY,
  upfit_delivery_coordination boolean DEFAULT false,
  floor_plan_limit numeric,
  typical_days_to_floor integer,
  average_turn_days integer,
  primary_contact_name character varying,
  primary_contact_title character varying,
  primary_contact_phone character varying,
  primary_contact_email character varying,
  cdk_dealer_id character varying,
  reynolds_dealer_id character varying,
  dms_provider character varying,
  dms_sync_enabled boolean DEFAULT false,
  b4a_account_number character varying,
  b4a_enrollment_date date,
  CONSTRAINT dealers_pkey PRIMARY KEY (id),
  CONSTRAINT dealers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES 01. Organization.organizations(id),
  CONSTRAINT dealers_last_profile_update_by_fkey FOREIGN KEY (last_profile_update_by) REFERENCES auth.users(id)
);
CREATE TABLE 02a. Dealership.listing_images (
  id bigint NOT NULL DEFAULT nextval('"02a. Dealership".listing_images_id_seq'::regclass),
  listing_id bigint NOT NULL,
  image_url character varying NOT NULL,
  thumbnail_url character varying,
  image_type character varying CHECK (image_type::text = ANY (ARRAY['exterior_front'::character varying::text, 'exterior_rear'::character varying::text, 'exterior_side_driver'::character varying::text, 'exterior_side_passenger'::character varying::text, 'exterior_overhead'::character varying::text, 'exterior_angle'::character varying::text, 'interior_front'::character varying::text, 'interior_rear'::character varying::text, 'interior_cargo'::character varying::text, 'interior_dashboard'::character varying::text, 'engine'::character varying::text, 'wheels'::character varying::text, 'undercarriage'::character varying::text, 'equipment_detail'::character varying::text, 'damage'::character varying::text, 'window_sticker'::character varying::text, 'other'::character varying::text])),
  caption text,
  alt_text character varying,
  display_order integer NOT NULL DEFAULT 0,
  is_primary boolean NOT NULL DEFAULT false,
  is_featured boolean NOT NULL DEFAULT false,
  width_px integer,
  height_px integer,
  file_size_bytes integer,
  format character varying,
  uploaded_by uuid,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT listing_images_pkey PRIMARY KEY (id),
  CONSTRAINT listing_images_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES 02a. Dealership.vehicle_listings(id),
  CONSTRAINT listing_images_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE 02a. Dealership.oem_invoice_fleet_credits (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  oem_invoice_id bigint NOT NULL,
  credit_type character varying NOT NULL,
  credit_description text,
  credit_amount numeric NOT NULL DEFAULT 0,
  reference_number character varying,
  is_on_invoice boolean DEFAULT true,
  line_number integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT oem_invoice_fleet_credits_pkey PRIMARY KEY (id),
  CONSTRAINT oem_invoice_fleet_credits_oem_invoice_id_fkey FOREIGN KEY (oem_invoice_id) REFERENCES 02a. Dealership.oem_invoices(id)
);
CREATE TABLE 02a. Dealership.oem_invoice_line_items (
  id bigint NOT NULL DEFAULT nextval('"02a. Dealership".oem_invoice_line_items_id_seq'::regclass),
  oem_invoice_id bigint NOT NULL,
  option_id bigint,
  option_code character varying NOT NULL,
  option_description text NOT NULL,
  option_category character varying,
  msrp_price numeric,
  invoice_price numeric,
  is_no_charge boolean DEFAULT false,
  is_standard_equipment boolean DEFAULT false,
  is_required boolean DEFAULT false,
  line_number integer,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  vehicle_config_option_id bigint,
  is_package_content boolean DEFAULT false,
  parent_line_number integer,
  discount_amount numeric DEFAULT 0,
  credit_amount numeric DEFAULT 0,
  data_source character varying DEFAULT 'invoice_scan'::character varying,
  CONSTRAINT oem_invoice_line_items_pkey PRIMARY KEY (id),
  CONSTRAINT oem_invoice_line_items_oem_invoice_id_fkey FOREIGN KEY (oem_invoice_id) REFERENCES 02a. Dealership.oem_invoices(id),
  CONSTRAINT oem_invoice_line_items_option_id_fkey FOREIGN KEY (option_id) REFERENCES 03. Vehicle Data.options(id),
  CONSTRAINT oem_invoice_line_items_vehicle_config_option_id_fkey FOREIGN KEY (vehicle_config_option_id) REFERENCES 03. Vehicle Data.vehicle_config_options(id)
);
CREATE TABLE 02a. Dealership.oem_invoices (
  id bigint NOT NULL DEFAULT nextval('"02a. Dealership".oem_invoices_id_seq'::regclass),
  dealer_order_id bigint NOT NULL,
  dealer_id bigint NOT NULL,
  organization_id bigint NOT NULL,
  invoice_number character varying NOT NULL UNIQUE,
  invoice_date date NOT NULL,
  vin character varying NOT NULL,
  invoice_type character varying NOT NULL CHECK (invoice_type::text = ANY (ARRAY['standard'::character varying, 'fleet_56a'::character varying, 'fleet_56m'::character varying, 'fleet_government'::character varying, 'b4a'::character varying, 'non_b4a'::character varying]::text[])),
  base_vehicle_msrp numeric NOT NULL,
  total_options_msrp numeric DEFAULT 0,
  destination_delivery_msrp numeric NOT NULL,
  subtotal_msrp numeric NOT NULL,
  base_vehicle_invoice numeric NOT NULL,
  total_options_invoice numeric DEFAULT 0,
  subtotal_invoice numeric NOT NULL,
  fuel_charge numeric DEFAULT 0,
  cv_lot_management numeric DEFAULT 0,
  advertising_assessment numeric DEFAULT 0,
  other_charges numeric DEFAULT 0,
  total_invoice numeric NOT NULL,
  holdback_amount numeric DEFAULT 0,
  holdback_percentage numeric DEFAULT 3.0,
  has_b4a boolean DEFAULT false,
  b4a_floor_plan_allowance numeric DEFAULT 0,
  b4a_holdback_credit numeric DEFAULT 0,
  b4a_options_holdback numeric DEFAULT 0,
  b4a_charge numeric DEFAULT 0,
  fleet_incentive_amount numeric DEFAULT 0,
  fleet_incentive_type character varying,
  competitive_price_allowance numeric DEFAULT 0,
  government_price_concession numeric DEFAULT 0,
  fleet_reference_number character varying,
  a_plan_price numeric,
  z_plan_price numeric,
  d_plan_price numeric,
  x_plan_price numeric,
  protected_invoice_amount numeric,
  net_dealer_cost numeric,
  shipping_weight_lbs integer,
  exterior_color_code character varying,
  exterior_color_name character varying,
  interior_color_code character varying,
  interior_color_name character varying,
  equipment_package_code character varying,
  invoice_pdf_url character varying,
  window_sticker_pdf_url character varying,
  payment_status character varying DEFAULT 'unpaid'::character varying CHECK (payment_status::text = ANY (ARRAY['unpaid'::character varying, 'floor_planned'::character varying, 'paid'::character varying, 'financed'::character varying]::text[])),
  floor_plan_date date,
  paid_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  sold_to_dealer_name character varying,
  dealer_address character varying,
  ship_to_address character varying,
  ship_through character varying,
  order_type character varying,
  buyer_code character varying,
  batch_id character varying,
  price_level character varying,
  invoice_prepared_date date,
  item_number character varying,
  transit_days integer,
  final_assembly_plant character varying,
  finance_company character varying,
  finance_account_number character varying,
  CONSTRAINT oem_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT oem_invoices_dealer_order_id_fkey FOREIGN KEY (dealer_order_id) REFERENCES 02a. Dealership.dealer_orders(id),
  CONSTRAINT oem_invoices_dealer_id_fkey FOREIGN KEY (dealer_id) REFERENCES 02a. Dealership.dealers(id),
  CONSTRAINT oem_invoices_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES 01. Organization.organizations(id)
);
CREATE TABLE 02a. Dealership.vehicle_listings (
  id bigint NOT NULL DEFAULT nextval('"02a. Dealership".vehicle_listings_id_seq'::regclass),
  dealer_id bigint NOT NULL,
  complete_configuration_id bigint NOT NULL,
  organization_id bigint NOT NULL,
  vin character varying NOT NULL UNIQUE CHECK (length(vin::text) = 17 AND vin::text ~ '^[A-HJ-NPR-Z0-9]{17}$'::text),
  stock_number character varying,
  condition character varying NOT NULL CHECK (condition::text = ANY (ARRAY['new'::character varying::text, 'used'::character varying::text, 'certified_pre_owned'::character varying::text, 'demo'::character varying::text, 'refurbished'::character varying::text])),
  mileage integer CHECK (mileage >= 0),
  year_in_service integer,
  exterior_color character varying,
  interior_color character varying,
  paint_condition character varying CHECK (paint_condition::text = ANY (ARRAY['excellent'::character varying::text, 'good'::character varying::text, 'fair'::character varying::text, 'poor'::character varying::text])),
  interior_condition character varying CHECK (interior_condition::text = ANY (ARRAY['excellent'::character varying::text, 'good'::character varying::text, 'fair'::character varying::text, 'poor'::character varying::text])),
  asking_price numeric NOT NULL CHECK (asking_price >= 0::numeric),
  special_price numeric CHECK (special_price >= 0::numeric),
  original_msrp numeric,
  price_type character varying NOT NULL DEFAULT 'negotiable'::character varying CHECK (price_type::text = ANY (ARRAY['fixed'::character varying::text, 'negotiable'::character varying::text, 'call_for_price'::character varying::text, 'auction'::character varying::text, 'lease_only'::character varying::text])),
  listing_title character varying,
  listing_description text,
  key_highlights ARRAY,
  marketing_headline character varying,
  dealer_notes text,
  location_name character varying,
  location_address character varying,
  location_city character varying,
  location_state character varying,
  location_zip character varying,
  location_latitude numeric,
  location_longitude numeric,
  listing_status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (listing_status::text = ANY (ARRAY['draft'::character varying::text, 'available'::character varying::text, 'pending'::character varying::text, 'sold'::character varying::text, 'removed'::character varying::text, 'archived'::character varying::text])),
  availability_status character varying DEFAULT 'in_stock'::character varying CHECK (availability_status::text = ANY (ARRAY['in_stock'::character varying::text, 'in_transit'::character varying::text, 'on_order'::character varying::text, 'at_upfitter'::character varying::text])),
  expected_arrival_date date,
  is_featured boolean NOT NULL DEFAULT false,
  is_certified boolean NOT NULL DEFAULT false,
  is_fleet_vehicle boolean NOT NULL DEFAULT false,
  is_commercial_use boolean NOT NULL DEFAULT true,
  is_hot_deal boolean DEFAULT false,
  is_clearance boolean DEFAULT false,
  view_count integer NOT NULL DEFAULT 0,
  inquiry_count integer NOT NULL DEFAULT 0,
  favorite_count integer NOT NULL DEFAULT 0,
  share_count integer NOT NULL DEFAULT 0,
  last_viewed_at timestamp with time zone,
  primary_image_url character varying,
  video_url character varying,
  virtual_tour_url character varying,
  brochure_url character varying,
  previous_owners integer,
  accident_history character varying CHECK (accident_history::text = ANY (ARRAY['none'::character varying::text, 'minor'::character varying::text, 'major'::character varying::text, 'unknown'::character varying::text])),
  accident_description text,
  service_records_available boolean DEFAULT false,
  service_history_summary text,
  carfax_report_url character varying,
  warranty_remaining boolean DEFAULT false,
  warranty_type character varying,
  warranty_expires_at date,
  warranty_miles_remaining integer,
  warranty_details text,
  financing_available boolean DEFAULT true,
  lease_available boolean DEFAULT false,
  estimated_monthly_payment numeric,
  down_payment_required numeric,
  apr_starting_at numeric,
  lease_term_months integer,
  qualifies_for_rebates boolean DEFAULT false,
  rebate_description text,
  qualifies_for_tax_credits boolean DEFAULT false,
  tax_credit_details text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  published_at timestamp with time zone,
  sold_at timestamp with time zone,
  removed_at timestamp with time zone,
  expires_at timestamp with time zone,
  dealer_inventory_id bigint,
  oem_invoice_id bigint,
  CONSTRAINT vehicle_listings_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_listings_complete_configuration_id_fkey FOREIGN KEY (complete_configuration_id) REFERENCES 05. Completed Unit Configuration.complete_configurations(id),
  CONSTRAINT vehicle_listings_dealer_id_fkey FOREIGN KEY (dealer_id) REFERENCES 02a. Dealership.dealers(id),
  CONSTRAINT vehicle_listings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES 01. Organization.organizations(id),
  CONSTRAINT vehicle_listings_dealer_inventory_id_fkey FOREIGN KEY (dealer_inventory_id) REFERENCES 02a. Dealership.dealer_inventory(id),
  CONSTRAINT vehicle_listings_oem_invoice_id_fkey FOREIGN KEY (oem_invoice_id) REFERENCES 02a. Dealership.oem_invoices(id)
);

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE 03. Vehicle Data.makes (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  make_name character varying NOT NULL UNIQUE,
  make_code character varying UNIQUE,
  manufacturer_legal_name character varying,
  parent_company character varying,
  headquarters_location character varying,
  country_of_origin character varying DEFAULT 'USA'::character varying,
  is_active boolean NOT NULL DEFAULT true,
  is_commercial_vehicle_manufacturer boolean NOT NULL DEFAULT true,
  specializes_in ARRAY,
  logo_url character varying,
  brand_color_hex character varying,
  website_url character varying,
  display_order integer DEFAULT 0,
  dealer_support_phone character varying,
  dealer_support_email character varying,
  dealer_portal_url character varying,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT makes_pkey PRIMARY KEY (id)
);
CREATE TABLE 03. Vehicle Data.options (
  id bigint NOT NULL DEFAULT nextval('"03. Vehicle Data".options_id_seq'::regclass),
  option_code character varying NOT NULL UNIQUE,
  option_name character varying NOT NULL,
  option_description text,
  category character varying NOT NULL,
  option_type character varying NOT NULL DEFAULT 'standalone'::character varying CHECK (option_type::text = ANY (ARRAY['package'::character varying::text, 'standalone'::character varying::text, 'delete'::character varying::text])),
  price numeric,
  is_package boolean NOT NULL DEFAULT false,
  parent_package_id bigint,
  available_note text,
  is_safety boolean NOT NULL DEFAULT false,
  is_performance boolean NOT NULL DEFAULT false,
  is_appearance boolean NOT NULL DEFAULT false,
  is_comfort boolean NOT NULL DEFAULT false,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying::text, 'discontinued'::character varying::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  dealer_invoice_price numeric,
  invoice_discount_percentage numeric,
  is_no_charge boolean DEFAULT false,
  CONSTRAINT options_pkey PRIMARY KEY (id),
  CONSTRAINT options_parent_package_id_fkey FOREIGN KEY (parent_package_id) REFERENCES 03. Vehicle Data.options(id)
);
CREATE TABLE 03. Vehicle Data.safety_ratings (
  id bigint NOT NULL DEFAULT nextval('"03. Vehicle Data".safety_ratings_id_seq'::regclass),
  vehicle_config_id bigint NOT NULL,
  overall_rating integer CHECK (overall_rating >= 1 AND overall_rating <= 5),
  frontal_driver_rating integer CHECK (frontal_driver_rating >= 1 AND frontal_driver_rating <= 5),
  frontal_passenger_rating integer CHECK (frontal_passenger_rating >= 1 AND frontal_passenger_rating <= 5),
  side_driver_rating integer CHECK (side_driver_rating >= 1 AND side_driver_rating <= 5),
  side_passenger_rating integer CHECK (side_passenger_rating >= 1 AND side_passenger_rating <= 5),
  rollover_rating integer CHECK (rollover_rating >= 1 AND rollover_rating <= 5),
  rollover_risk_percentage numeric,
  test_year integer,
  test_report_url character varying,
  iihs_overall_rating character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT safety_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT safety_ratings_vehicle_config_id_fkey FOREIGN KEY (vehicle_config_id) REFERENCES 03. Vehicle Data.vehicle_config(id)
);
CREATE TABLE 03. Vehicle Data.standard_options (
  id bigint NOT NULL DEFAULT nextval('"03. Vehicle Data".standard_options_id_seq'::regclass),
  vehicle_config_id bigint NOT NULL,
  category character varying NOT NULL,
  feature_name character varying NOT NULL,
  feature_code character varying,
  display_order integer DEFAULT 0,
  is_safety_feature boolean NOT NULL DEFAULT false,
  is_required_disclosure boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT standard_options_pkey PRIMARY KEY (id),
  CONSTRAINT standard_options_vehicle_config_id_fkey FOREIGN KEY (vehicle_config_id) REFERENCES 03. Vehicle Data.vehicle_config(id)
);
CREATE TABLE 03. Vehicle Data.vehicle (
  id bigint NOT NULL DEFAULT nextval('"03. Vehicle Data".vehicle_id_seq'::regclass),
  year integer NOT NULL CHECK (year >= 2000 AND year <= 2099),
  make_name character varying NOT NULL,
  model_name character varying NOT NULL,
  series_name character varying,
  vehicle_type character varying NOT NULL,
  gvwr_class character varying,
  payload_range character varying,
  starting_msrp numeric,
  seating_range character varying,
  marketing_description text,
  is_commercial boolean NOT NULL DEFAULT true,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying::text, 'discontinued'::character varying::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  make_id bigint,
  model_id bigint,
  CONSTRAINT vehicle_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_make_id_fkey FOREIGN KEY (make_id) REFERENCES 03. Vehicle Data.vehicle_makes(id),
  CONSTRAINT vehicle_model_id_fkey FOREIGN KEY (model_id) REFERENCES 03. Vehicle Data.vehicle_models(id)
);
CREATE TABLE 03. Vehicle Data.vehicle_config (
  id bigint NOT NULL DEFAULT nextval('"03. Vehicle Data".vehicle_config_id_seq'::regclass),
  vehicle_id bigint NOT NULL,
  wheelbase_inches numeric,
  height_type character varying,
  gvwr_package character varying,
  body_style character varying,
  config_name character varying NOT NULL,
  config_code character varying,
  base_msrp numeric NOT NULL,
  base_curb_weight_lbs integer,
  gvwr_lbs integer NOT NULL,
  payload_capacity_lbs integer NOT NULL,
  seating_capacity integer NOT NULL,
  engine_description character varying,
  transmission character varying,
  drive_type character varying,
  axle_description character varying,
  rear_wheels character varying,
  battery_kwh numeric,
  battery_voltage numeric,
  range_miles integer,
  horsepower integer,
  torque_ftlbs integer,
  mpg_city numeric,
  mpg_highway numeric,
  mpge integer,
  length_inches numeric,
  width_inches numeric,
  height_inches numeric,
  is_available boolean NOT NULL DEFAULT true,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying::text, 'inactive'::character varying::text])),
  data_source character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  trim_level character varying,
  destination_delivery_charge numeric DEFAULT 2595.00,
  typical_holdback_percentage numeric DEFAULT 3.0,
  shipping_weight_lbs integer,
  mpg_combined numeric,
  fuel_tank_capacity_gallons numeric,
  annual_fuel_cost_estimate numeric,
  co2_emissions_grams_per_mile numeric,
  epa_smog_rating integer CHECK (epa_smog_rating >= 1 AND epa_smog_rating <= 10),
  epa_greenhouse_rating integer CHECK (epa_greenhouse_rating >= 1 AND epa_greenhouse_rating <= 10),
  basic_warranty_years integer DEFAULT 3,
  basic_warranty_miles integer DEFAULT 36000,
  powertrain_warranty_years integer DEFAULT 5,
  powertrain_warranty_miles integer DEFAULT 60000,
  CONSTRAINT vehicle_config_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_config_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES 03. Vehicle Data.vehicle(id)
);
CREATE TABLE 03. Vehicle Data.vehicle_config_options (
  id bigint NOT NULL DEFAULT nextval('"03. Vehicle Data".vehicle_config_options_id_seq'::regclass),
  vehicle_config_id bigint NOT NULL,
  option_id bigint NOT NULL,
  price_override numeric,
  is_recommended boolean NOT NULL DEFAULT false,
  compatibility_note character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vehicle_config_options_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_config_options_option_id_fkey FOREIGN KEY (option_id) REFERENCES 03. Vehicle Data.options(id),
  CONSTRAINT vehicle_config_options_vehicle_config_id_fkey FOREIGN KEY (vehicle_config_id) REFERENCES 03. Vehicle Data.vehicle_config(id)
);
CREATE TABLE 03. Vehicle Data.vehicle_makes (
  id bigint NOT NULL DEFAULT nextval('"03. Vehicle Data".vehicle_makes_id_seq'::regclass),
  make_name character varying NOT NULL UNIQUE CHECK (length(TRIM(BOTH FROM make_name)) > 0),
  make_name_normalized character varying NOT NULL UNIQUE,
  country_of_origin character varying,
  parent_company character varying,
  founded_year integer CHECK (founded_year >= 1800 AND founded_year::numeric <= EXTRACT(year FROM CURRENT_DATE)),
  official_name character varying,
  logo_url character varying,
  brand_description text,
  website_url character varying,
  manufactures_commercial_trucks boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer DEFAULT 0,
  slug character varying UNIQUE,
  meta_description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vehicle_makes_pkey PRIMARY KEY (id)
);
CREATE TABLE 03. Vehicle Data.vehicle_models (
  id bigint NOT NULL DEFAULT nextval('"03. Vehicle Data".vehicle_models_id_seq'::regclass),
  make_id bigint NOT NULL,
  model_name character varying NOT NULL CHECK (length(TRIM(BOTH FROM model_name)) > 0),
  model_name_normalized character varying NOT NULL,
  model_type character varying,
  body_style_category character varying,
  first_model_year integer,
  last_model_year integer,
  official_name character varying,
  model_description text,
  primary_image_url character varying,
  brochure_url character varying,
  is_commercial_vehicle boolean NOT NULL DEFAULT false,
  is_cab_chassis boolean NOT NULL DEFAULT false,
  is_cutaway boolean NOT NULL DEFAULT false,
  target_industry jsonb,
  gvwr_class_range character varying,
  typical_applications jsonb,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer DEFAULT 0,
  slug character varying,
  meta_description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vehicle_models_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_models_make_id_fkey FOREIGN KEY (make_id) REFERENCES 03. Vehicle Data.vehicle_makes(id)
);

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE 04. Equipment Data.equipment (
  id bigint NOT NULL DEFAULT nextval('"04. Equipment Data".equipment_id_seq'::regclass),
  upfitter_name character varying NOT NULL,
  product_line character varying NOT NULL,
  model_name character varying NOT NULL,
  equipment_type character varying NOT NULL,
  equipment_subtype character varying,
  primary_material character varying NOT NULL,
  body_category character varying,
  application_type character varying,
  length_range_min_inches numeric,
  length_range_max_inches numeric,
  width_range_min_inches numeric,
  width_range_max_inches numeric,
  height_range_min_inches numeric,
  height_range_max_inches numeric,
  weight_range_min_lbs integer,
  weight_range_max_lbs integer,
  starting_msrp numeric,
  typical_price_range_low numeric,
  typical_price_range_high numeric,
  marketing_description text,
  key_features jsonb,
  target_industries jsonb,
  primary_image_url character varying,
  thumbnail_url character varying,
  brochure_pdf_url character varying,
  video_url character varying,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying::text, 'discontinued'::character varying::text, 'coming_soon'::character varying::text])),
  is_featured boolean NOT NULL DEFAULT false,
  availability_status character varying,
  typical_lead_time_days integer,
  slug character varying UNIQUE,
  meta_title character varying,
  meta_description text,
  search_keywords text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  discontinued_at timestamp with time zone,
  CONSTRAINT equipment_pkey PRIMARY KEY (id)
);
CREATE TABLE 04. Equipment Data.equipment_config (
  id bigint NOT NULL DEFAULT nextval('"04. Equipment Data".equipment_config_id_seq'::regclass),
  equipment_id bigint NOT NULL,
  config_name character varying NOT NULL,
  config_code character varying,
  model_number character varying,
  length_inches numeric NOT NULL,
  width_inches numeric NOT NULL,
  height_inches numeric NOT NULL,
  interior_length_inches numeric,
  interior_width_inches numeric,
  interior_height_inches numeric,
  usable_volume_cubic_feet numeric,
  equipment_weight_lbs integer NOT NULL CHECK (equipment_weight_lbs > 0),
  maximum_payload_lbs integer,
  minimum_cab_to_axle_inches numeric,
  maximum_cab_to_axle_inches numeric,
  recommended_cab_to_axle_inches numeric,
  mounting_type character varying,
  requires_subframe boolean NOT NULL DEFAULT false,
  compatible_gvwr_min integer,
  compatible_gvwr_max integer,
  compatible_chassis_classes jsonb,
  compatible_cab_types jsonb,
  compatible_bed_lengths jsonb,
  compatible_drive_types jsonb,
  compartment_count integer,
  drawer_count integer,
  shelf_count integer,
  door_configuration character varying,
  material character varying NOT NULL,
  gauge_thickness character varying,
  coating_finish character varying,
  corrosion_protection character varying,
  tool_compartment_volume_cubic_feet numeric,
  door_style character varying,
  locking_mechanism character varying,
  has_interior_lighting boolean NOT NULL DEFAULT false,
  has_exterior_lighting boolean NOT NULL DEFAULT false,
  has_power_outlets boolean NOT NULL DEFAULT false,
  electrical_system_voltage integer,
  has_crane_provisions boolean NOT NULL DEFAULT false,
  crane_mounting_location character varying,
  max_crane_capacity_lbs integer,
  has_ladder_rack_provisions boolean NOT NULL DEFAULT false,
  ladder_rack_type character varying,
  has_stake_pockets boolean NOT NULL DEFAULT false,
  has_tie_downs boolean NOT NULL DEFAULT false,
  tie_down_count integer,
  front_axle_weight_distribution_lbs integer,
  rear_axle_weight_distribution_lbs integer,
  center_of_gravity_from_rear_axle_inches numeric,
  base_msrp numeric NOT NULL,
  dealer_cost numeric,
  installation_labor_hours numeric,
  estimated_installation_cost numeric,
  is_active boolean NOT NULL DEFAULT true,
  is_in_stock boolean NOT NULL DEFAULT false,
  lead_time_days integer NOT NULL DEFAULT 30,
  minimum_order_quantity integer NOT NULL DEFAULT 1,
  meets_fmvss boolean NOT NULL DEFAULT true,
  fmvss_compliance_notes text,
  dot_approved boolean NOT NULL DEFAULT true,
  certification_documents jsonb,
  image_urls jsonb,
  installation_manual_url character varying,
  spec_sheet_url character varying,
  cad_drawing_url character varying,
  notes text,
  internal_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT equipment_config_pkey PRIMARY KEY (id),
  CONSTRAINT equipment_config_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES 04. Equipment Data.equipment(id)
);
CREATE TABLE 04. Equipment Data.equipment_config_options (
  id bigint NOT NULL DEFAULT nextval('"04. Equipment Data".equipment_config_options_id_seq'::regclass),
  equipment_config_id bigint NOT NULL,
  option_id bigint NOT NULL,
  is_available boolean NOT NULL DEFAULT true,
  is_required boolean NOT NULL DEFAULT false,
  is_default boolean NOT NULL DEFAULT false,
  is_popular boolean NOT NULL DEFAULT false,
  price_override numeric,
  discount_percentage numeric,
  installation_time_override_hours numeric,
  installation_notes text,
  compatibility_notes text,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT equipment_config_options_pkey PRIMARY KEY (id),
  CONSTRAINT equipment_config_options_equipment_config_id_fkey FOREIGN KEY (equipment_config_id) REFERENCES 04. Equipment Data.equipment_config(id),
  CONSTRAINT equipment_config_options_option_id_fkey FOREIGN KEY (option_id) REFERENCES 04. Equipment Data.equipment_options(id)
);
CREATE TABLE 04. Equipment Data.equipment_options (
  id bigint NOT NULL DEFAULT nextval('"04. Equipment Data".equipment_options_id_seq'::regclass),
  option_category character varying NOT NULL,
  option_name character varying NOT NULL,
  option_code character varying UNIQUE,
  option_description text,
  supplier_name character varying,
  weight_lbs integer NOT NULL DEFAULT 0,
  length_impact_inches numeric NOT NULL DEFAULT 0,
  width_impact_inches numeric NOT NULL DEFAULT 0,
  height_impact_inches numeric NOT NULL DEFAULT 0,
  installation_type character varying,
  installation_complexity character varying,
  installation_time_hours numeric,
  requires_drilling boolean NOT NULL DEFAULT false,
  requires_welding boolean NOT NULL DEFAULT false,
  requires_electrical_work boolean NOT NULL DEFAULT false,
  specifications jsonb,
  capacity_rating integer,
  voltage_requirement integer,
  amperage_draw numeric,
  compatible_materials jsonb,
  compatible_equipment_types jsonb,
  incompatible_option_ids jsonb,
  msrp numeric NOT NULL,
  dealer_cost numeric,
  installation_cost numeric,
  is_active boolean NOT NULL DEFAULT true,
  is_popular boolean NOT NULL DEFAULT false,
  availability_status character varying,
  lead_time_days integer NOT NULL DEFAULT 0,
  image_url character varying,
  installation_guide_url character varying,
  spec_sheet_url character varying,
  marketing_tagline character varying,
  benefits text,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT equipment_options_pkey PRIMARY KEY (id)
);
CREATE TABLE 04. Equipment Data.standard_features (
  id bigint NOT NULL DEFAULT nextval('"04. Equipment Data".standard_features_id_seq'::regclass),
  equipment_config_id bigint NOT NULL,
  feature_category character varying NOT NULL,
  feature_name character varying NOT NULL,
  feature_description text,
  feature_specification character varying,
  quantity integer NOT NULL DEFAULT 1,
  location character varying,
  estimated_value numeric,
  weight_contribution_lbs integer NOT NULL DEFAULT 0,
  is_highlighted boolean NOT NULL DEFAULT false,
  display_order integer NOT NULL DEFAULT 0,
  icon_name character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT standard_features_pkey PRIMARY KEY (id),
  CONSTRAINT standard_features_equipment_config_id_fkey FOREIGN KEY (equipment_config_id) REFERENCES 04. Equipment Data.equipment_config(id)
);

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE 05. Completed Unit Configuration.chassis_equipment_compatibility (
  id bigint NOT NULL DEFAULT nextval('"05. Completed Unit Configuration".chassis_equipment_compatibility_id_seq'::regclass),
  vehicle_config_id bigint NOT NULL,
  equipment_config_id bigint NOT NULL,
  compatibility_status character varying NOT NULL DEFAULT 'compatible'::character varying CHECK (compatibility_status::text = ANY (ARRAY['compatible'::character varying::text, 'requires_modification'::character varying::text, 'not_compatible'::character varying::text])),
  compatibility_confidence character varying NOT NULL DEFAULT 'verified'::character varying CHECK (compatibility_confidence::text = ANY (ARRAY['verified'::character varying::text, 'calculated'::character varying::text, 'estimated'::character varying::text])),
  gvwr_compliant boolean NOT NULL DEFAULT true,
  gawr_compliant boolean NOT NULL DEFAULT true,
  cab_to_axle_compatible boolean NOT NULL DEFAULT true,
  wheelbase_compatible boolean NOT NULL DEFAULT true,
  total_combined_weight_lbs integer,
  front_axle_weight_lbs integer,
  rear_axle_weight_lbs integer,
  payload_remaining_lbs integer,
  requires_modifications boolean NOT NULL DEFAULT false,
  modification_description text,
  modification_cost_estimate numeric,
  installation_method character varying,
  installation_complexity character varying,
  installation_time_hours numeric,
  oem_approved boolean NOT NULL DEFAULT false,
  upfitter_certified boolean NOT NULL DEFAULT true,
  certification_documents jsonb,
  warranty_impact text,
  installation_cost_estimate numeric,
  total_package_msrp numeric,
  compatibility_notes text,
  internal_notes text,
  installation_guide_url character varying,
  verified_by character varying,
  verification_date date,
  last_reviewed_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT chassis_equipment_compatibility_pkey PRIMARY KEY (id),
  CONSTRAINT chassis_equipment_compatibility_equipment_config_id_fkey FOREIGN KEY (equipment_config_id) REFERENCES 04. Equipment Data.equipment_config(id),
  CONSTRAINT chassis_equipment_compatibility_vehicle_config_id_fkey FOREIGN KEY (vehicle_config_id) REFERENCES 03. Vehicle Data.vehicle_config(id)
);
CREATE TABLE 05. Completed Unit Configuration.complete_configurations (
  id bigint NOT NULL DEFAULT nextval('"05. Completed Unit Configuration".complete_configurations_id_seq'::regclass),
  configuration_name character varying NOT NULL,
  configuration_type character varying NOT NULL CHECK (configuration_type::text = ANY (ARRAY['stock_unit'::character varying::text, 'build_to_order'::character varying::text, 'upfitter_build'::character varying::text, 'cab_chassis'::character varying::text])),
  vehicle_config_id bigint NOT NULL,
  equipment_config_id bigint,
  owner_type character varying NOT NULL CHECK (owner_type::text = ANY (ARRAY['dealer'::character varying::text, 'upfitter'::character varying::text, 'fleet'::character varying::text, 'system'::character varying::text])),
  owner_name character varying,
  build_status character varying NOT NULL DEFAULT 'configured'::character varying CHECK (build_status::text = ANY (ARRAY['configured'::character varying::text, 'in_build'::character varying::text, 'completed'::character varying::text, 'in_inventory'::character varying::text])),
  is_complete boolean NOT NULL DEFAULT false,
  selected_vehicle_option_ids jsonb,
  selected_equipment_option_ids jsonb,
  total_vehicle_weight_lbs integer,
  total_equipment_weight_lbs integer,
  total_combined_weight_lbs integer NOT NULL,
  front_axle_weight_lbs integer NOT NULL,
  rear_axle_weight_lbs integer NOT NULL,
  payload_capacity_remaining_lbs integer NOT NULL CHECK (payload_capacity_remaining_lbs >= 0),
  gvwr_compliant boolean NOT NULL,
  front_gawr_compliant boolean NOT NULL,
  rear_gawr_compliant boolean NOT NULL,
  fmvss_compliant boolean NOT NULL DEFAULT true,
  compliance_notes text,
  chassis_cost numeric NOT NULL,
  equipment_cost numeric,
  vehicle_options_cost numeric,
  equipment_options_cost numeric,
  installation_cost numeric,
  total_cost numeric NOT NULL CHECK (total_cost >= 0::numeric),
  msrp numeric NOT NULL CHECK (msrp >= 0::numeric),
  dealer_pricing numeric,
  estimated_delivery_days integer,
  build_start_date date,
  estimated_completion_date date,
  actual_completion_date date,
  vin character varying UNIQUE,
  unit_number character varying,
  stock_number character varying,
  build_sheet_url character varying,
  spec_sheet_url character varying,
  configuration_pdf_url character varying,
  primary_image_url character varying,
  additional_images jsonb,
  notes text,
  internal_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT complete_configurations_pkey PRIMARY KEY (id),
  CONSTRAINT complete_configurations_equipment_config_id_fkey FOREIGN KEY (equipment_config_id) REFERENCES 04. Equipment Data.equipment_config(id),
  CONSTRAINT complete_configurations_vehicle_config_id_fkey FOREIGN KEY (vehicle_config_id) REFERENCES 03. Vehicle Data.vehicle_config(id)
);

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE auth.audit_log_entries (
  instance_id uuid,
  id uuid NOT NULL,
  payload json,
  created_at timestamp with time zone,
  ip_address character varying NOT NULL DEFAULT ''::character varying,
  CONSTRAINT audit_log_entries_pkey PRIMARY KEY (id)
);
CREATE TABLE auth.flow_state (
  id uuid NOT NULL,
  user_id uuid,
  auth_code text NOT NULL,
  code_challenge_method USER-DEFINED NOT NULL,
  code_challenge text NOT NULL,
  provider_type text NOT NULL,
  provider_access_token text,
  provider_refresh_token text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  authentication_method text NOT NULL,
  auth_code_issued_at timestamp with time zone,
  CONSTRAINT flow_state_pkey PRIMARY KEY (id)
);
CREATE TABLE auth.identities (
  provider_id text NOT NULL,
  user_id uuid NOT NULL,
  identity_data jsonb NOT NULL,
  provider text NOT NULL,
  last_sign_in_at timestamp with time zone,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  email text DEFAULT lower((identity_data ->> 'email'::text)),
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT identities_pkey PRIMARY KEY (id),
  CONSTRAINT identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE auth.instances (
  id uuid NOT NULL,
  uuid uuid,
  raw_base_config text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  CONSTRAINT instances_pkey PRIMARY KEY (id)
);
CREATE TABLE auth.mfa_amr_claims (
  session_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  authentication_method text NOT NULL,
  id uuid NOT NULL,
  CONSTRAINT mfa_amr_claims_pkey PRIMARY KEY (id),
  CONSTRAINT mfa_amr_claims_session_id_fkey FOREIGN KEY (session_id) REFERENCES auth.sessions(id)
);
CREATE TABLE auth.mfa_challenges (
  id uuid NOT NULL,
  factor_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL,
  verified_at timestamp with time zone,
  ip_address inet NOT NULL,
  otp_code text,
  web_authn_session_data jsonb,
  CONSTRAINT mfa_challenges_pkey PRIMARY KEY (id),
  CONSTRAINT mfa_challenges_auth_factor_id_fkey FOREIGN KEY (factor_id) REFERENCES auth.mfa_factors(id)
);
CREATE TABLE auth.mfa_factors (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  friendly_name text,
  factor_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  secret text,
  phone text,
  last_challenged_at timestamp with time zone UNIQUE,
  web_authn_credential jsonb,
  web_authn_aaguid uuid,
  last_webauthn_challenge_data jsonb,
  CONSTRAINT mfa_factors_pkey PRIMARY KEY (id),
  CONSTRAINT mfa_factors_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE auth.oauth_authorizations (
  id uuid NOT NULL,
  authorization_id text NOT NULL UNIQUE,
  client_id uuid NOT NULL,
  user_id uuid,
  redirect_uri text NOT NULL CHECK (char_length(redirect_uri) <= 2048),
  scope text NOT NULL CHECK (char_length(scope) <= 4096),
  state text CHECK (char_length(state) <= 4096),
  resource text CHECK (char_length(resource) <= 2048),
  code_challenge text CHECK (char_length(code_challenge) <= 128),
  code_challenge_method USER-DEFINED,
  response_type USER-DEFINED NOT NULL DEFAULT 'code'::auth.oauth_response_type,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::auth.oauth_authorization_status,
  authorization_code text UNIQUE CHECK (char_length(authorization_code) <= 255),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '00:03:00'::interval),
  approved_at timestamp with time zone,
  CONSTRAINT oauth_authorizations_pkey PRIMARY KEY (id),
  CONSTRAINT oauth_authorizations_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.oauth_clients(id),
  CONSTRAINT oauth_authorizations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE auth.oauth_clients (
  id uuid NOT NULL,
  client_secret_hash text,
  registration_type USER-DEFINED NOT NULL,
  redirect_uris text NOT NULL,
  grant_types text NOT NULL,
  client_name text CHECK (char_length(client_name) <= 1024),
  client_uri text CHECK (char_length(client_uri) <= 2048),
  logo_uri text CHECK (char_length(logo_uri) <= 2048),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  client_type USER-DEFINED NOT NULL DEFAULT 'confidential'::auth.oauth_client_type,
  CONSTRAINT oauth_clients_pkey PRIMARY KEY (id)
);
CREATE TABLE auth.oauth_consents (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  client_id uuid NOT NULL,
  scopes text NOT NULL CHECK (char_length(scopes) <= 2048),
  granted_at timestamp with time zone NOT NULL DEFAULT now(),
  revoked_at timestamp with time zone,
  CONSTRAINT oauth_consents_pkey PRIMARY KEY (id),
  CONSTRAINT oauth_consents_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.oauth_clients(id),
  CONSTRAINT oauth_consents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE auth.one_time_tokens (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  token_type USER-DEFINED NOT NULL,
  token_hash text NOT NULL CHECK (char_length(token_hash) > 0),
  relates_to text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT one_time_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT one_time_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE auth.refresh_tokens (
  instance_id uuid,
  id bigint NOT NULL DEFAULT nextval('auth.refresh_tokens_id_seq'::regclass),
  token character varying UNIQUE,
  user_id character varying,
  revoked boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  parent character varying,
  session_id uuid,
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT refresh_tokens_session_id_fkey FOREIGN KEY (session_id) REFERENCES auth.sessions(id)
);
CREATE TABLE auth.saml_providers (
  id uuid NOT NULL,
  sso_provider_id uuid NOT NULL,
  entity_id text NOT NULL UNIQUE CHECK (char_length(entity_id) > 0),
  metadata_xml text NOT NULL CHECK (char_length(metadata_xml) > 0),
  metadata_url text CHECK (metadata_url = NULL::text OR char_length(metadata_url) > 0),
  attribute_mapping jsonb,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  name_id_format text,
  CONSTRAINT saml_providers_pkey PRIMARY KEY (id),
  CONSTRAINT saml_providers_sso_provider_id_fkey FOREIGN KEY (sso_provider_id) REFERENCES auth.sso_providers(id)
);
CREATE TABLE auth.saml_relay_states (
  id uuid NOT NULL,
  sso_provider_id uuid NOT NULL,
  request_id text NOT NULL CHECK (char_length(request_id) > 0),
  for_email text,
  redirect_to text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  flow_state_id uuid,
  CONSTRAINT saml_relay_states_pkey PRIMARY KEY (id),
  CONSTRAINT saml_relay_states_flow_state_id_fkey FOREIGN KEY (flow_state_id) REFERENCES auth.flow_state(id),
  CONSTRAINT saml_relay_states_sso_provider_id_fkey FOREIGN KEY (sso_provider_id) REFERENCES auth.sso_providers(id)
);
CREATE TABLE auth.schema_migrations (
  version character varying NOT NULL,
  CONSTRAINT schema_migrations_pkey PRIMARY KEY (version)
);
CREATE TABLE auth.sessions (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  factor_id uuid,
  aal USER-DEFINED,
  not_after timestamp with time zone,
  refreshed_at timestamp without time zone,
  user_agent text,
  ip inet,
  tag text,
  oauth_client_id uuid,
  refresh_token_hmac_key text,
  refresh_token_counter bigint,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_oauth_client_id_fkey FOREIGN KEY (oauth_client_id) REFERENCES auth.oauth_clients(id),
  CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE auth.sso_domains (
  id uuid NOT NULL,
  sso_provider_id uuid NOT NULL,
  domain text NOT NULL CHECK (char_length(domain) > 0),
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  CONSTRAINT sso_domains_pkey PRIMARY KEY (id),
  CONSTRAINT sso_domains_sso_provider_id_fkey FOREIGN KEY (sso_provider_id) REFERENCES auth.sso_providers(id)
);
CREATE TABLE auth.sso_providers (
  id uuid NOT NULL,
  resource_id text CHECK (resource_id = NULL::text OR char_length(resource_id) > 0),
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  disabled boolean,
  CONSTRAINT sso_providers_pkey PRIMARY KEY (id)
);
CREATE TABLE auth.users (
  instance_id uuid,
  id uuid NOT NULL,
  aud character varying,
  role character varying,
  email character varying,
  encrypted_password character varying,
  email_confirmed_at timestamp with time zone,
  invited_at timestamp with time zone,
  confirmation_token character varying,
  confirmation_sent_at timestamp with time zone,
  recovery_token character varying,
  recovery_sent_at timestamp with time zone,
  email_change_token_new character varying,
  email_change character varying,
  email_change_sent_at timestamp with time zone,
  last_sign_in_at timestamp with time zone,
  raw_app_meta_data jsonb,
  raw_user_meta_data jsonb,
  is_super_admin boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  phone text DEFAULT NULL::character varying UNIQUE,
  phone_confirmed_at timestamp with time zone,
  phone_change text DEFAULT ''::character varying,
  phone_change_token character varying DEFAULT ''::character varying,
  phone_change_sent_at timestamp with time zone,
  confirmed_at timestamp with time zone DEFAULT LEAST(email_confirmed_at, phone_confirmed_at),
  email_change_token_current character varying DEFAULT ''::character varying,
  email_change_confirm_status smallint DEFAULT 0 CHECK (email_change_confirm_status >= 0 AND email_change_confirm_status <= 2),
  banned_until timestamp with time zone,
  reauthentication_token character varying DEFAULT ''::character varying,
  reauthentication_sent_at timestamp with time zone,
  is_sso_user boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  is_anonymous boolean NOT NULL DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE realtime.messages (
  topic text NOT NULL,
  extension text NOT NULL,
  payload jsonb,
  event text,
  private boolean DEFAULT false,
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  inserted_at timestamp without time zone NOT NULL DEFAULT now(),
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT messages_pkey PRIMARY KEY (id, inserted_at)
);
CREATE TABLE realtime.schema_migrations (
  version bigint NOT NULL,
  inserted_at timestamp without time zone,
  CONSTRAINT schema_migrations_pkey PRIMARY KEY (version)
);
CREATE TABLE realtime.subscription (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  subscription_id uuid NOT NULL,
  entity regclass NOT NULL,
  filters ARRAY NOT NULL DEFAULT '{}'::realtime.user_defined_filter[],
  claims jsonb NOT NULL,
  claims_role regrole NOT NULL DEFAULT realtime.to_regrole((claims ->> 'role'::text)),
  created_at timestamp without time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT subscription_pkey PRIMARY KEY (id)
);

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE storage.buckets (
  id text NOT NULL,
  name text NOT NULL,
  owner uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  public boolean DEFAULT false,
  avif_autodetection boolean DEFAULT false,
  file_size_limit bigint,
  allowed_mime_types ARRAY,
  owner_id text,
  type USER-DEFINED NOT NULL DEFAULT 'STANDARD'::storage.buckettype,
  CONSTRAINT buckets_pkey PRIMARY KEY (id)
);
CREATE TABLE storage.buckets_analytics (
  name text NOT NULL,
  type USER-DEFINED NOT NULL DEFAULT 'ANALYTICS'::storage.buckettype,
  format text NOT NULL DEFAULT 'ICEBERG'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  deleted_at timestamp with time zone,
  CONSTRAINT buckets_analytics_pkey PRIMARY KEY (id)
);
CREATE TABLE storage.buckets_vectors (
  id text NOT NULL,
  type USER-DEFINED NOT NULL DEFAULT 'VECTOR'::storage.buckettype,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT buckets_vectors_pkey PRIMARY KEY (id)
);
CREATE TABLE storage.migrations (
  id integer NOT NULL,
  name character varying NOT NULL UNIQUE,
  hash character varying NOT NULL,
  executed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT migrations_pkey PRIMARY KEY (id)
);
CREATE TABLE storage.objects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bucket_id text,
  name text,
  owner uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_accessed_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  path_tokens ARRAY DEFAULT string_to_array(name, '/'::text),
  version text,
  owner_id text,
  user_metadata jsonb,
  level integer,
  CONSTRAINT objects_pkey PRIMARY KEY (id),
  CONSTRAINT objects_bucketId_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id)
);
CREATE TABLE storage.prefixes (
  bucket_id text NOT NULL,
  name text NOT NULL,
  level integer NOT NULL DEFAULT storage.get_level(name),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT prefixes_pkey PRIMARY KEY (bucket_id, level, name),
  CONSTRAINT prefixes_bucketId_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id)
);
CREATE TABLE storage.s3_multipart_uploads (
  id text NOT NULL,
  in_progress_size bigint NOT NULL DEFAULT 0,
  upload_signature text NOT NULL,
  bucket_id text NOT NULL,
  key text NOT NULL,
  version text NOT NULL,
  owner_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_metadata jsonb,
  CONSTRAINT s3_multipart_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT s3_multipart_uploads_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id)
);
CREATE TABLE storage.s3_multipart_uploads_parts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  upload_id text NOT NULL,
  size bigint NOT NULL DEFAULT 0,
  part_number integer NOT NULL,
  bucket_id text NOT NULL,
  key text NOT NULL,
  etag text NOT NULL,
  owner_id text,
  version text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT s3_multipart_uploads_parts_pkey PRIMARY KEY (id),
  CONSTRAINT s3_multipart_uploads_parts_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id),
  CONSTRAINT s3_multipart_uploads_parts_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES storage.s3_multipart_uploads(id)
);
CREATE TABLE storage.vector_indexes (
  id text NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  bucket_id text NOT NULL,
  data_type text NOT NULL,
  dimension integer NOT NULL,
  distance_metric text NOT NULL,
  metadata_configuration jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vector_indexes_pkey PRIMARY KEY (id),
  CONSTRAINT vector_indexes_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets_vectors(id)
);

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE supabase_migrations.schema_migrations (
  version text NOT NULL,
  statements ARRAY,
  name text,
  CONSTRAINT schema_migrations_pkey PRIMARY KEY (version)
);
CREATE TABLE supabase_migrations.seed_files (
  path text NOT NULL,
  hash text NOT NULL,
  CONSTRAINT seed_files_pkey PRIMARY KEY (path)
);

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE vault.secrets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  description text NOT NULL DEFAULT ''::text,
  secret text NOT NULL,
  key_id uuid,
  nonce bytea DEFAULT vault._crypto_aead_det_noncegen(),
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT secrets_pkey PRIMARY KEY (id)
);
