-- Migration: Create listing-images storage bucket
-- Note: Supabase storage buckets cannot be created via SQL
-- This file documents the required bucket configuration
-- 
-- To create the bucket, use one of these methods:
--
-- Method 1: Supabase Dashboard (Recommended)
-- 1. Go to your Supabase project dashboard
-- 2. Navigate to Storage
-- 3. Click "New bucket"
-- 4. Configure:
--    - Name: listing-images
--    - Public bucket: Yes (checked)
--    - File size limit: 52428800 (50MB)
--    - Allowed MIME types: image/jpeg, image/png, image/gif, image/webp
-- 5. Click "Create bucket"
--
-- Method 2: Supabase CLI
-- Run: supabase storage create listing-images --public
--
-- Method 3: Programmatically (requires service role key)
-- Use the Supabase Management API or client with service role key
-- Example:
--   const { data, error } = await supabase.storage.createBucket('listing-images', {
--     public: true,
--     fileSizeLimit: 52428800,
--     allowedMimeTypes: ['image/jpeg', 'image/png', 'image/gif', 'image/webp']
--   });

-- This migration file serves as documentation only
-- The bucket must be created manually through the Supabase Dashboard or CLI

